services:
  server:
    build: 
      dockerfile: docker/Dockerfile
      context: .
    image: covertovert:latest
    hostname: receiver
    container_name: receiver
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - "8000:8000"
    volumes:
      - ./code:/app:rw
      - ./examples:/examples:rw
  client:
    build: 
      dockerfile: docker/Dockerfile
      context: .
    image: covertovert:latest
    hostname: sender
    container_name: sender
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./code:/app:rw
      - ./examples:/examples:rw